description:
	echo "The flag is the filename of a file, which can be found in a file which 4 beginning regular size unsigned integers that add up to 0xdeadbeef" > README
package:
	tar cvf programming100.tar "a lot of files/" --mtime=0
	tar rf programming100.tar README

clean:
	rm programming100.tar


